version: "3.3"

services:
  app:
    container_name: "app"
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 7134:7134
    stdin_open: true
    environment:
      - PORT=7134
      - RDS_HOSTNAME=database-1.cp0accsqw0of.sa-east-1.rds.amazonaws.com
      - RDS_USER=admin
      - RDS_PASSWORD=M0jokerto1
      - RDS_DATABASE=internship
      - RDS_PORT=3306
    command: npm run dev
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - RDS_HOSTNAME=database-1.cp0accsqw0of.sa-east-1.rds.amazonaws.com
      - RDS_USER=admin
      - RDS_PASSWORD=
      - RDS_DATABASE=internship
      - RDS_PORT=3306

volumes:
  node_modules:
  mysql-data:
